version: '3.7'

services:
  app:
    build: .
    image: round-robin-ex:develop
    command: /bin/sh -c "uvicorn --host=0.0.0.0 --port=8005 app.main:app"
    volumes:
      - .:/usr/src/app
    ports:
      - 8005:8005
    networks:
      - net

networks:
  net: